"""Export processed analysis outputs as docs/data.js for the static site.

Usage:
    python -m src.export_site
"""

import json

import pandas as pd

from src.config import DATA_PROCESSED, ROOT, TOPIC_LEXICONS

SITE = ROOT / "docs"

THEME_LABELS = {
    "ui_ux": "UI / UX",
    "performance": "Crashes & lag",
    "onboarding_kyc": "Onboarding / KYC",
    "customer_support": "Support",
    "charges_fees": "Charges & fees",
    "ai_features": "AI features",
    "trust_security": "Trust & security",
}


def main() -> None:
    scores = pd.read_csv(DATA_PROCESSED / "firm_scores.csv")
    panel = pd.read_csv(DATA_PROCESSED / "broker_panel.csv")
    with open(DATA_PROCESSED / "model_results.json") as f:
        model = json.load(f)

    clients = dict(zip(panel["firm"], panel["active_clients_2026"]))
    growth = dict(zip(panel["firm"], panel["growth_pct"]))

    firms = []
    for _, r in scores.sort_values("experience_score", ascending=False).iterrows():
        firms.append(
            {
                "firm": r["firm"],
                "category": r["category"],
                "score": round(float(r["experience_score"]), 1),
                "rating": float(r["play_rating"]),
                "sentiment": float(r["mean_sentiment"]),
                "painRate": float(r["pain_rate"]),
                "aiRate": float(r["ai_mention_rate"]),
                "clients": int(clients[r["firm"]]) if r["firm"] in clients else None,
                "growthPct": round(float(growth[r["firm"]]), 2) if r["firm"] in growth else None,
                "themes": {t: round(100 * float(r[f"neg_{t}_rate"]), 2) for t in TOPIC_LEXICONS},
            }
        )

    data = {
        "generated": "July 2026",
        "nReviews": int(scores["n_reviews_analyzed"].sum()),
        "nApps": int(len(scores)),
        "aiSharePct": round(
            100 * float((scores["ai_mention_rate"] * scores["n_reviews_analyzed"]).sum()
                        / scores["n_reviews_analyzed"].sum()), 2),
        "themeLabels": THEME_LABELS,
        "model": {
            "slope": model["slope_pp_per_point"],
            "intercept": model["intercept"],
            "r2": model["r_squared"],
            "ci": model["slope_ci_95"],
            "nFirms": model["n_firms"],
            "targetP75": model["target_score_p75"],
        },
        "firms": firms,
    }

    SITE.mkdir(exist_ok=True)
    with open(SITE / "data.js", "w") as f:
        f.write("// Generated by src/export_site.py — do not edit by hand\n")
        f.write("const DATA = " + json.dumps(data, indent=1) + ";\n")
    print(f"Wrote {SITE / 'data.js'} ({len(firms)} firms)")


if __name__ == "__main__":
    main()
